name       : playonlinux
version    : '4.4'
release    : 20
source     :
    - https://github.com/PlayOnLinux/POL-POM-4/archive/refs/tags/4.4.tar.gz : a3536243772002d17b9c5fcfd616844134bcfe126ce7b7b24eb971ba1f63365d
license    : GPL-3.0-or-later
component  : gaming
summary    : PlayOnLinux is a piece of software which allows you to easily install and use numerous games and apps
description: |
    PlayOnLinux is a piece of software which allows you to easily install and use numerous games and apps designed to run with Microsoft Windows.
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(x11)
    - pkgconfig(xorg-server)
rundeps    :
    - cabextract
    - icoutils
    - imagemagick
    - jq
    - netcat
    - p7zip
    - python-natsort
    - wine-32bit
    - wxPython
setup      : |
    cp $pkgfiles/Makefile .
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/applications/PlayOnLinux.desktop
    install -D -m 00644 $pkgfiles/playonlinux.desktop $installdir/usr/share/applications/playonlinux.desktop
