name       : playonlinux
version    : 4.2.12
release    : 9
source     :
    - https://github.com/PlayOnLinux/POL-POM-4/archive/4.2.12.tar.gz : 85a333495cb338687062406cd13411b3199a6ac6561391436088175264479a24
license    : GPL-3.0
component  : gaming
summary    : PlayOnLinux is a piece of software which allows you to easily install
    and use numerous games and apps
description: |
    PlayOnLinux is a piece of software which allows you to easily install and use numerous games and apps designed to run with Microsoft Windows.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(x11)
    - pkgconfig(xorg-server)
rundeps    :
    - cabextract
    - icoutils
    - imagemagick
    - netcat
    - p7zip
    - wine-32bit
    - wxPython
setup      : |
    cp $pkgfiles/Makefile .
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/applications/PlayOnLinux.desktop
    install -D -m 00644 $pkgfiles/playonlinux.desktop $installdir/usr/share/applications/playonlinux.desktop
