name       : playonlinux
version    : 4.3.4
release    : 16
source     :
    - https://github.com/PlayOnLinux/POL-POM-4/archive/4.3.4.tar.gz : 6f61cfded993f54be12a433c0f571f05aa1fa775f02ec15c5c3547aca3110083
license    : GPL-3.0-or-later
component  : gaming
summary    : PlayOnLinux is a piece of software which allows you to easily install
    and use numerous games and apps
description: |
    PlayOnLinux is a piece of software which allows you to easily install and use numerous games and apps designed to run with Microsoft Windows.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xorg-server)
rundeps    :
    - cabextract
    - icoutils
    - imagemagick
    - jq
    - netcat
    - p7zip
    - wine-32bit
    - wxPython
setup      : |
    cp $pkgfiles/Makefile .
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/applications/PlayOnLinux.desktop
    install -D -m 00644 $pkgfiles/playonlinux.desktop $installdir/usr/share/applications/playonlinux.desktop
